/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JProgressBar;

/**
 *
 * @author maikr
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalProdutosCadastrados = new javax.swing.JLabel();
        prTotalProdutosCadastrados = new javax.swing.JProgressBar();
        mnbMenuBar = new javax.swing.JMenuBar();
        mnProduto = new javax.swing.JMenu();
        mnIncluir = new javax.swing.JMenuItem();
        mnListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");
        setPreferredSize(new java.awt.Dimension(291, 240));

        lblTotalProdutosCadastrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalProdutosCadastrados.setText("Total de produtos cadastrados: 00");
        lblTotalProdutosCadastrados.setToolTipText("");
        lblTotalProdutosCadastrados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        prTotalProdutosCadastrados.setPreferredSize(new java.awt.Dimension(181, 4));

        mnProduto.setText("Produto");

        mnIncluir.setText("Incluir");
        mnProduto.add(mnIncluir);

        mnListar.setText("Listar");
        mnProduto.add(mnListar);

        mnbMenuBar.add(mnProduto);

        setJMenuBar(mnbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalProdutosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(prTotalProdutosCadastrados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(prTotalProdutosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalProdutosCadastrados))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMnIncluir() {
        return mnIncluir;
    }

    public JMenuItem getMnListar() {
        return mnListar;
    }

    public JLabel getLblTotalProdutosCadastrados() {
        return lblTotalProdutosCadastrados;
    }
    
    public JProgressBar getPrTotalProdutosCadastrados() {
        return prTotalProdutosCadastrados;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTotalProdutosCadastrados;
    private javax.swing.JMenuItem mnIncluir;
    private javax.swing.JMenuItem mnListar;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenuBar mnbMenuBar;
    private javax.swing.JProgressBar prTotalProdutosCadastrados;
    // End of variables declaration//GEN-END:variables
}
